# Generated by Django 4.2.5 on 2023-09-19 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='std',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='manager.student'),
            preserve_default=False,
        ),
    ]
