# Generated by Django 4.2.5 on 2023-09-19 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_books_std'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='deadline',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='books',
            name='std',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='manager.student'),
        ),
    ]
