# Generated by Django 4.2.5 on 2023-09-19 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0003_books_deadline_alter_books_std'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='id',
            new_name='std_id',
        ),
    ]
