# Generated by Django 4.2.5 on 2023-09-19 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0004_rename_id_student_std_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='std_id',
            new_name='id',
        ),
    ]
