# Generated by Django 4.2.5 on 2023-09-19 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0005_rename_std_id_student_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='std',
        ),
        migrations.CreateModel(
            name='borrow',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('num_papers', models.IntegerField()),
                ('type', models.CharField(max_length=20)),
                ('deadline', models.CharField(max_length=20, null=True)),
                ('std', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='manager.student')),
            ],
        ),
    ]
