# Generated by Django 4.2.5 on 2023-09-19 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0006_remove_books_std_borrow'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='deadline',
        ),
    ]
