# Generated by Django 4.2.5 on 2023-09-19 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0007_remove_books_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='deadline',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='books',
            name='std',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='manager.student'),
        ),
        migrations.DeleteModel(
            name='borrow',
        ),
    ]
