# Generated by Django 4.2.5 on 2023-09-19 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0008_books_deadline_books_std_delete_borrow'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='borrowed',
            field=models.BooleanField(default=False),
        ),
    ]
