# Generated by Django 4.2.5 on 2023-09-19 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0009_books_borrowed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='num_papers',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='age',
            field=models.PositiveIntegerField(),
        ),
    ]
